# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_sparseHC <- function(S, method = "average", noOrder = FALSE) {
    .Call('sparseHC_run_sparseHC', PACKAGE = 'sparseHC', S, method, noOrder)
}

