# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgCIsSymmetric <- function(S, eps) {
    .Call('sparseAHC_dgCIsSymmetric', PACKAGE = 'sparseAHC', S, eps)
}

run_sparseAHC <- function(S, method = "average") {
    .Call('sparseAHC_run_sparseAHC', PACKAGE = 'sparseAHC', S, method)
}

